version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1

jobs:
  setup:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Generate CircleCI config & build Dockerfile(s) if changed
          command: cd .circleci && ./setup.sh
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml

workflows:
  setup:
    jobs:
      - setup